# Defaults for this cop are found here:
# https://github.com/rubocop/rubocop/blob/master/config/default.yml
#
# Add customizations below.
#
# Ensure to document why we change a default by linking the corresponding PR.
# For example:
#
#     Naming/VariableNumber:
#       Enabled: true
#

# @NOTE: changed EnforcedStyle from "normalcase" to "snake_case"
# https://github.com/dbl-works/rubocop-dbl/pull/26
Naming/VariableNumber:
  EnforcedStyle: snake_case
