# Defaults for this cop are found here:
# https://github.com/rubocop/rubocop-performance/blob/master/config/default.yml
#
# Add customizations below.
#
# Ensure to document why we change a default by linking the corresponding PR.
# For example:
#
#     Performance/AncestorsInclude:
#       Enabled: true
#
