# Defaults for this cop are found here:
# https://github.com/rubocop/rubocop-rails/blob/master/config/default.yml
#
# Add customizations below.
#
# Ensure to document why we change a default by linking the corresponding PR.
# For example:
#
#     Rails/ActionFilter:
#       Reference: 'https://github.com/dbl-works/rubocop-dbl/pull/33'
#       Enabled: false
#

# @NOTE: added: "staging"
Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test
    - staging

# @NOTE: disabled
Rails/HttpStatus:
  Reference: 'We have no reference for this change'
  Enabled: false

# @NOTE: disabled
Rails/ApplicationController:
  Reference: 'We have no reference for this change'
  Enabled: false


#
# @NOTE: all the cops ahead are "pending" in the current default config
#
Rails/ActiveRecordCallbacksOrder:
  Reference: 'We have no reference for this change'
  Enabled: true

Rails/AfterCommitOverride:
  Reference: 'We have no reference for this change'
  Enabled: true

Rails/AttributeDefaultBlockValue:
  Reference: 'We have no reference for this change'
  Enabled: true

Rails/FindById:
  Reference: 'We have no reference for this change'
  Enabled: true

Rails/Inquiry:
  Reference: 'We have no reference for this change'
  Enabled: true

Rails/MailerName:
  Reference: 'We have no reference for this change'
  Enabled: true

Rails/MatchRoute:
  Reference: 'We have no reference for this change'
  Enabled: true

Rails/NegateInclude:
  Reference: 'We have no reference for this change'
  Enabled: true

Rails/Pluck:
  Reference: 'We have no reference for this change'
  Enabled: true

Rails/PluckInWhere:
  Reference: 'We have no reference for this change'
  Enabled: true

Rails/RenderInline:
  Reference: 'We have no reference for this change'
  Enabled: true

Rails/RenderPlainText:
  Reference: 'We have no reference for this change'
  Enabled: true

Rails/ShortI18n:
  Reference: 'We have no reference for this change'
  Enabled: true
  EnforcedStyle: aggressive

Rails/SquishedSQLHeredocs:
  Reference: 'We have no reference for this change'
  Enabled: true

Rails/WhereEquals:
  Reference: 'We have no reference for this change'
  Enabled: true

Rails/WhereExists:
  Reference: 'We have no reference for this change'
  Enabled: true

Rails/WhereNot:
  Reference: 'We have no reference for this change'
  Enabled: true
