# Defaults for this cop are found here:
# https://github.com/rubocop/rubocop-rspec/blob/master/config/default.yml
#
# Add customizations below.
#
# Ensure to document why we change a default by linking the corresponding PR.
# For example:
#
#     RSpec/AlignLeftLetBrace:
#       Enabled: true
#


# @NOTE: added: "if", "and"
RSpec/ContextWording:
  Prefixes:
    - when
    - with
    - without
    - if
    - and


# @NOTE: by default, no methods are enabled
RSpec/Capybara/FeatureMethods:
  EnabledMethods:
    - feature
    - scenario

# @NOTE: increased from 3 to 5
RSpec/NestedGroups:
  Max: 5


# @NOTE: increased from 5 to 6
RSpec/MultipleMemoizedHelpers:
  Max: 6
