# Defaults for this cop are found here:
# https://github.com/rubocop/rubocop/blob/master/config/default.yml
#
# Add customizations below.
#
# Ensure to document why we change a default by linking the corresponding PR.
# For example:
#
#     Style/AndOr:
#       Enabled: true
#

Sorbet/HasSigil:
  MinimumStrictness: strict
  SuggestedStrictness: strict
  Exclude:
    - "spec/**/*"
    - "test/**/*"

Sorbet/StrictSigil:
  Enabled: true
  Exclude:
    - "spec/**/*"
    - "lib/tasks/**/*"
