name: Test
on: [push]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "2.6"
          - "2.7"
          - "3.1"
          - "3.2"
        gemfile:
          - gemfiles/rubocop_1.24.gemfile
          - gemfiles/rubocop_1.7.gemfile
          - gemfiles/rails_6.1.gemfile
          - gemfiles/rails_7.0.gemfile
        exclude:
          # rails 7 requires ruby >= 2.7
          - ruby: 2.6
            gemfile: gemfiles/rails_7.0.gemfile
          # fatal error with: 1.7.0 (using Parser 3.1.0.0, rubocop-ast 1.15.1, running on ruby 3.1.0 x86_64-linux)
          - ruby: 3.1
            gemfile: gemfiles/rubocop_1.7.gemfile
          - ruby: 3.2
            gemfile: gemfiles/rubocop_1.7.gemfile
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-${{ matrix.ruby }}-${{ matrix.gemfile }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: bundle install
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install -j $(getconf _NPROCESSORS_ONLN) --retry 3

      - name: Run Test
        run: bundle exec rake

      - name: Run Changelog linter
        run: bundle exec parse CHANGELOG.md
